# Generated by Django 6.0.4 on 2026-05-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('titulo_academico', models.CharField(max_length=150)),
                ('biografia', models.TextField()),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('dedicacion', models.CharField(max_length=150)),
            ],
        ),
    ]
