# Generated by Django 6.0.4 on 2026-05-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombres')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Carrera')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='profile', verbose_name='Imagen')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'db_table': 'profile',
            },
        ),
        migrations.AlterModelOptions(
            name='portafolio',
            options={'ordering': ['-created'], 'verbose_name': 'Portafolio', 'verbose_name_plural': 'Portafolios'},
        ),
        migrations.AddField(
            model_name='portafolio',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portafolio', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación'),
        ),
        migrations.AlterModelTable(
            name='portafolio',
            table='portfolio',
        ),
    ]
